### ISSUE TITLE
katateIDE.configureClasspath not found

### ISSUE THREAD

**Issue by jamesbontempo** [ZenWave360/karate-jar#1]
Hi there.

I'm having the hardest time getting Karate working w/Visual Studio Code. I figured the easiest thing to do would be to use KarateIDE & this Jar, but after installing the two & trying to configure the Classpath via the Command Palette (View > Command Palette> KarateIDE: Configure Classpath) I'm getting the following error:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/1130423/190516105-c21e9792-9cfd-4970-aa01-aeeb253b4cef.png">

Do you have any idea what's going on here & how I can fix it?

BTW, this is on a Mac.

**Comment by ivangsa** [comment]
Hi @jamesbontempo 

I will look into it ASAP

in the time being you can add this line to file `.vscode/settings.json` to configure it manually

```json
"karateIDE.karateCli.classpath": "src/test/java:src/test/resources:target/classes:target/test-classes:${ext:karate-ide.jar}"
```

Please note the expresion `${ext:karate-ide.jar}` at the end of the setting... It will use jar downloaded from the extension but you could change it with a the path (absolute or relative to the workspace) of any other karate.jar you may want to use

I'll look into this as son as posible

Thanks for reporting this

**Comment by ivangsa** [comment]
I can confirm that there is an issue activating the extension when the workspace does not contain any karate files (like karate-config.js, features...)

If you open a workspace with features or create a new one, the command should be available

I will release a version fixing this in the coming days

Thanks again for finding this..

**Comment by jamesbontempo** [comment]
Ahhh...

I hadn't started building anything, yet, I was just getting the environment set up. Once I created a very basic config file it worked. But yeah, perhaps it would be nice if setting the Classpath via the Command Palette worked even if there weren't any Karate files in the project.

Thanks for the quick & very helpful response!

**Comment by ivangsa** [comment]
Hi @jamesbontempo 

I have release a fix for this issue...

It would be helpful if you can leave a review or some stars on the extension marketplace page
It will take you only 1 minute
https://marketplace.visualstudio.com/items?itemName=KarateIDE.karate-ide&ssr=false#review-details

Thanks a lot
Ivan

**Comment by jamesbontempo** [comment]
Great! I just left a review :)
